# Generated by Django 4.2.5 on 2024-03-31 16:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customer", "0002_alter_customer_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.AlterModelOptions(
            name="orders",
            options={"verbose_name_plural": "Orders"},
        ),
    ]
