# Generated by Django 4.2.5 on 2024-03-31 16:32

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("business", "0002_alter_business_mobile_alter_business_user_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="business",
            options={"verbose_name_plural": "Businesses"},
        ),
    ]
